In [1]:
# importing the libraries
import numpy as np
import pandas as pd

# function that takes file name as input and returns a processed dataframe
def process_file(file):
    data = pd.read_csv(file)

    # Selecting the actual required columns for further processing
    # Selecting the actual required columns for further processing
    data = data[[
        'InertialMeasurementUnit RUA accX', 'InertialMeasurementUnit RUA accY', 'InertialMeasurementUnit RUA accZ',
        'InertialMeasurementUnit RUA gyroX', 'InertialMeasurementUnit RUA gyroY', 'InertialMeasurementUnit RUA gyroZ',
        'InertialMeasurementUnit RUA magneticX', 'InertialMeasurementUnit RUA magneticY', 'InertialMeasurementUnit RUA magneticZ',
        'InertialMeasurementUnit RUA Quaternion1', 'InertialMeasurementUnit RUA Quaternion2', 'InertialMeasurementUnit RUA Quaternion3', 'InertialMeasurementUnit RUA Quaternion4', 
        'InertialMeasurementUnit RLA accX', 'InertialMeasurementUnit RLA accY', 'InertialMeasurementUnit RLA accZ', 
        'InertialMeasurementUnit RLA gyroX', 'InertialMeasurementUnit RLA gyroY', 'InertialMeasurementUnit RLA gyroZ',
        'InertialMeasurementUnit RLA magneticX', 'InertialMeasurementUnit RLA magneticY', 'InertialMeasurementUnit RLA magneticZ', 
        'InertialMeasurementUnit RLA Quaternion1', 'InertialMeasurementUnit RLA Quaternion2', 'InertialMeasurementUnit RLA Quaternion3', 'InertialMeasurementUnit RLA Quaternion4',
        'InertialMeasurementUnit LUA accX', 'InertialMeasurementUnit LUA accY', 'InertialMeasurementUnit LUA accZ',
        'InertialMeasurementUnit LUA gyroX', 'InertialMeasurementUnit LUA gyroY', 'InertialMeasurementUnit LUA gyroZ',
        'InertialMeasurementUnit LUA magneticX', 'InertialMeasurementUnit LUA magneticY', 'InertialMeasurementUnit LUA magneticZ',
        'InertialMeasurementUnit LUA Quaternion1', 'InertialMeasurementUnit LUA Quaternion2', 'InertialMeasurementUnit LUA Quaternion3', 'InertialMeasurementUnit LUA Quaternion4', 'InertialMeasurementUnit LLA accX', 'InertialMeasurementUnit LLA accY', 'InertialMeasurementUnit LLA accZ', 'InertialMeasurementUnit LLA gyroX', 'InertialMeasurementUnit LLA gyroY', 'InertialMeasurementUnit LLA gyroZ', 'InertialMeasurementUnit LLA magneticX', 'InertialMeasurementUnit LLA magneticY', 'InertialMeasurementUnit LLA magneticZ', 'InertialMeasurementUnit LLA Quaternion1', 'InertialMeasurementUnit LLA Quaternion2', 'InertialMeasurementUnit LLA Quaternion3', 'InertialMeasurementUnit LLA Quaternion4',
        'Accelerometer DOOR1 accX', 'Accelerometer DOOR1 accY', 'Accelerometer DOOR1 accZ',
        'Accelerometer DOOR2 accX', 'Accelerometer DOOR2 accY', 'Accelerometer DOOR2 accZ',
        'Locomotion', 'LL_Left_Arm_Object', 'LL_Right_Arm_Object', 'ML_Both_Arms'
        ]]
    
    # Drop rows where 'LL_Left_Arm', 'LL_Left_Arm_Object', 'LL_Right_Arm', 'LL_Right_Arm_Object', 'ML_Both_Arms' are all 0
    # data = data[(data['LL_Left_Arm_Object'] != 0) | (data['LL_Right_Arm_Object'] != 0) | (data['ML_Both_Arms'] != 0)]

    # drop rows where 'Locomotion' is 0
    data = data[data['Locomotion'] != 0]

    # drop the rows with missing values
    data = data.dropna()

    # drop rows that contain unwanted records in 'ML_Both_Arms'
    data = data[~data['LL_Left_Arm_Object'].isin([301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 318, 319, 320, 321, 322, 323])]

    # drop rows that contain unwanted records in 'ML_Both_Arms'
    data = data[~data['LL_Right_Arm_Object'].isin([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 518, 519, 520, 521, 522, 523])]

    # drop rows that contain unwanted records in 'ML_Both_Arms'
    data = data[~data['ML_Both_Arms'].isin([406520, 404520, 406505, 404505, 406519, 404519, 406511, 404511, 406508, 404508, 408512, 407521, 405506])]

    return data

In [2]:
# creating a dataset by combinig all files

# list all files in dataset folder
import os
import glob
import pandas as pd
file_names = os.listdir('dataset')

In [3]:
# creating a training and testing dataset
one = 0
two = 0
three = 0
four = 0
five = 0

for file in file_names:
    # process the file
    data = process_file('dataset/' + file)
    # append the data to the csv file according to file name
    # list unique values in 'Locomotion' column
    print(data['Locomotion'].unique(), end = ' ')
    if file.split('-')[0] == 'S1':
        if one == 0:
            data.to_csv('S1.csv', index=False)
            one = 1
        else:
            data.to_csv('S1.csv', mode='a', header=False, index=False)
    elif file.split('-')[0] == 'S2':
        if two == 0:
            data.to_csv('S2.csv', index=False)
            two = 1
        else:
            data.to_csv('S2.csv', mode='a', header=False, index=False)
    elif file.split('-')[0] == 'S3':
        if three == 0:
            data.to_csv('S3.csv', index=False)
            three = 1
        else:
            data.to_csv('S3.csv', mode='a', header=False, index=False)
    elif file.split('-')[0] == 'S4':
        if four == 0:
            data.to_csv('S4.csv', index=False)
            four = 1
        else:
            data.to_csv('S4.csv', mode='a', header=False, index=False)
    print(file, 'processed')

[2 1 4 5] S4-ADL1.csv processed
[2 1 4] S4-Drill.csv processed
[2 1 4 5] S4-ADL2.csv processed
[2 5 4 1] S4-ADL3.csv processed
[2 1 4] S2-Drill.csv processed
[2 1 4 5] S4-ADL4.csv processed
[2 1 4 5] S4-ADL5.csv processed
[2 1 5 4] S2-ADL4.csv processed
[2 1 4 5] S3-ADL4.csv processed
[1 2 4 5] S3-ADL5.csv processed
[2 1 5 4] S2-ADL5.csv processed
[1 2 4 5] S2-ADL1.csv processed
[2 1 4 5] S3-ADL1.csv processed
[2 1 4] S3-Drill.csv processed
[2 1 4 5] S3-ADL2.csv processed
[2 1 4 5] S2-ADL2.csv processed
[2 5 1 4] S2-ADL3.csv processed
[2 1 4 5] S3-ADL3.csv processed
[1 2 5 4] S1-ADL2.csv processed
[1 2 5 4] S1-ADL3.csv processed
[1 2 5 4] S1-ADL1.csv processed
[1 2 5 4] S1-ADL4.csv processed
[1 2 5 4] S1-ADL5.csv processed
[2 1 4] S1-Drill.csv processed
